apiVersion: v1
kind: Service
metadata:
  # Name of the service
  name: hello-world-service
spec:
  selector:
    # Selector to match the pods with the label 'app: hello-world'
    app: hello-world
  ports:
    # Protocol for the service port, typically TCP
    - protocol: TCP
      # Port that the service will expose
      port: 80
      # Port on the container that the service should forward traffic to
      targetPort: 8080
  # Service type, which creates an external load balancer
  type: LoadBalancer
