on:
  push:
    branches:
      - deploy-to-vm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Test with Maven
        run: mvn test

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.GCP_SSH_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} << 'EOF'
            echo "Stopping any running app..."
            pkill -f app.jar || true

            echo "Deleting existing JAR file if it exists..."
            rm -f /home/${{ secrets.GCP_SSH_USERNAME }}/app.jar

            echo "Updating system packages..."
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jre-headless
          EOF

      - name: Copy JAR to VM
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem target/*.jar ${{ secrets.GCP_SSH_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }}:/home/${{ secrets.GCP_SSH_USERNAME }}/app.jar

      - name: Start Application
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.GCP_SSH_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} << 'EOF'
            echo "Starting new application..."
            nohup java -jar /home/${{ secrets.GCP_SSH_USERNAME }}/app.jar > app.log 2>&1 &
          EOF
